# This is a basic workflow to help you get started with Actions

name: Testing the Trigger script

on:
  workflow_dispatch:
    inputs:
      IZ_ENV:
        description: 'Env to deploy the App'
        required: true
        default: 'qa'
      RECORD_NAME:
        description: 'Name of the App'
        required: true
        default: 'aie-st-app'
      WHEEL_VERSION:
        description: 'WHEEL_VERSION of the App'
        required: true
        default: '2023.02.14'  
        
# Controls when the workflow will run
# on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:
#     types: do-something

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "The IZ_ENV to deploy the app is : ${{ github.event.inputs.IZ_ENV }}"
          echo "The RECORD_NAME to deploy the app is : ${{ github.event.inputs.RECORD_NAME }}"
          echo "The WHEEL_VERSION to deploy the app is : ${{ github.event.inputs.WHEEL_VERSION }}"
